import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sadhak/isar_service.dart';
import 'package:sadhak/test_result.dart';
import 'report_models.dart';
import 'dart:typed_data';

class PdfGenerator {
  /// Basic quick test report (simple version)
  static Future<File> generateTestReport({
    required String testName,
    required String score,
    required DateTime date,
    required String feedback,
    required String performanceTrend,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        margin: const pw.EdgeInsets.all(32),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              "Athlete Performance Report",
              style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 16),
            pw.Text("Test Name: $testName"),
            pw.Text("Date: ${date.toLocal()}".split(' ')[0]),
            pw.SizedBox(height: 8),

            pw.Text("Score:", style: pw.TextStyle(fontSize: 18)),
            pw.Text(
              score,
              style: pw.TextStyle(
                fontSize: 28,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.green,
              ),
            ),
            pw.SizedBox(height: 20),

            pw.Text(
              "Performance Insight:",
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(feedback),
            pw.SizedBox(height: 10),

            pw.Text(
              "Progress Trend:",
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(performanceTrend),
            pw.SizedBox(height: 20),

            pw.Divider(),

            pw.Center(
              child: pw.Text(
                "Generated by Sādhak Performance App",
                style: pw.TextStyle(fontSize: 12, color: PdfColors.grey),
              ),
            ),
          ],
        ),
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File("${dir.path}/$testName-report.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  /// Full detailed report using TestReport model + historical graph & table
  static Future<void> generateAndShareReport(TestReport reportData) async {
    final pdf = pw.Document();
    final isar = IsarService();

    // Get historical results for this test
    final all = await isar.getAllTestResults();
    final results =
        all.where((r) => r.testTitle == reportData.testTitle).toList()
          ..sort((a, b) => a.date.compareTo(b.date));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.symmetric(horizontal: 28, vertical: 24),
        footer: (context) => _buildFooter(context),
        build: (context) {
          return [
            _buildHeader(reportData.testTitle),
            pw.SizedBox(height: 16),
            _buildHeadline(reportData.headlineResult, reportData.resultSummary),
            if (results.isNotEmpty) ...[
              pw.SizedBox(height: 12),
              _buildStatsSummary(results),
            ],
            pw.SizedBox(height: 12),
            if (reportData.breakdownMetrics.isNotEmpty)
              _buildSection(
                'Performance Breakdown',
                reportData.breakdownMetrics,
              ),
            if (reportData.comparisonMetrics.isNotEmpty)
              _buildSection('Comparison', reportData.comparisonMetrics),
            if (reportData.coachTips.isNotEmpty)
              _buildCoachTips(reportData.coachTips),
            if (results.isNotEmpty) ...[
              pw.SizedBox(height: 16),
              _buildHistoricalPerformance('Historical Performance', results),
            ],
          ];
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: '${reportData.testTitle.replaceAll(" ", "_")}_report.pdf',
    );
  }

  /// Build a single test detailed report PDF as bytes for server upload
  static Future<Uint8List> buildSingleReportPdfBytes(
    TestReport reportData,
  ) async {
    final pdf = pw.Document();
    final isar = IsarService();
    final all = await isar.getAllTestResults();
    final results =
        all.where((r) => r.testTitle == reportData.testTitle).toList()
          ..sort((a, b) => a.date.compareTo(b.date));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.symmetric(horizontal: 28, vertical: 24),
        footer: (context) => _buildFooter(context),
        build: (context) {
          return [
            _buildHeader(reportData.testTitle),
            pw.SizedBox(height: 16),
            _buildHeadline(reportData.headlineResult, reportData.resultSummary),
            if (results.isNotEmpty) ...[
              pw.SizedBox(height: 12),
              _buildStatsSummary(results),
            ],
            pw.SizedBox(height: 12),
            if (reportData.breakdownMetrics.isNotEmpty)
              _buildSection(
                'Performance Breakdown',
                reportData.breakdownMetrics,
              ),
            if (reportData.comparisonMetrics.isNotEmpty)
              _buildSection('Comparison', reportData.comparisonMetrics),
            if (reportData.coachTips.isNotEmpty)
              _buildCoachTips(reportData.coachTips),
            if (results.isNotEmpty) ...[
              pw.SizedBox(height: 16),
              _buildHistoricalPerformance('Previous Attempts', results),
            ],
          ];
        },
      ),
    );
    return pdf.save();
  }

  /// Generate a consolidated PDF for every test with stored results
  static Future<void> generateAndShareAllReports() async {
    try {
      final pdf = pw.Document();
      final isar = IsarService();
      final all = await isar.getAllTestResults();
      final byTest = <String, List<TestResult>>{};
      for (final r in all) {
        byTest.putIfAbsent(r.testTitle, () => []).add(r);
      }
      final titles = byTest.keys.toList()
        ..sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
      for (final t in titles) {
        byTest[t]!.sort((a, b) => a.date.compareTo(b.date));
      }

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.symmetric(horizontal: 28, vertical: 24),
          footer: (context) => _buildFooter(context),
          build: (context) {
            final widgets = <pw.Widget>[];
            widgets.add(_buildHeader('All Tests Report'));
            if (titles.isEmpty) {
              widgets.add(pw.SizedBox(height: 12));
              widgets.add(
                pw.Text(
                  'No test results found.',
                  style: pw.TextStyle(color: PdfColors.grey700),
                ),
              );
              return widgets;
            }
            for (final title in titles) {
              final results = byTest[title]!;
              widgets.add(pw.SizedBox(height: 16));
              widgets.add(
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              );
              widgets.add(pw.SizedBox(height: 6));
              widgets.add(_buildStatsSummary(results));
              widgets.add(pw.SizedBox(height: 10));
              widgets.add(
                _buildHistoricalPerformance('Historical Performance', results),
              );
              widgets.add(pw.Divider());
            }
            return widgets;
          },
        ),
      );

      await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: 'All_Tests_Report.pdf',
      );
    } catch (e) {
      // Fallback: build minimal error PDF so user still gets a file/share sheet
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          build: (c) => pw.Center(
            child: pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Text(
                  'Failed to build consolidated report',
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 12),
                pw.Text(
                  'Error: $e',
                  style: pw.TextStyle(color: PdfColors.red, fontSize: 12),
                ),
              ],
            ),
          ),
        ),
      );
      await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: 'All_Tests_Report_error.pdf',
      );
    }
  }

  /// Build the consolidated report as raw bytes (for upload to a server)
  static Future<Uint8List> buildAllReportsPdfBytes() async {
    try {
      final pdf = pw.Document();
      final isar = IsarService();
      final all = await isar.getAllTestResults();
      final byTest = <String, List<TestResult>>{};
      for (final r in all) {
        byTest.putIfAbsent(r.testTitle, () => []).add(r);
      }
      final titles = byTest.keys.toList()
        ..sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
      for (final t in titles) {
        byTest[t]!.sort((a, b) => a.date.compareTo(b.date));
      }

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.symmetric(horizontal: 28, vertical: 24),
          footer: (context) => _buildFooter(context),
          build: (context) {
            final widgets = <pw.Widget>[];
            widgets.add(_buildHeader('All Tests Report'));
            if (titles.isEmpty) {
              widgets.add(pw.SizedBox(height: 12));
              widgets.add(
                pw.Text(
                  'No test results found.',
                  style: pw.TextStyle(color: PdfColors.grey700),
                ),
              );
              return widgets;
            }
            for (final title in titles) {
              final results = byTest[title]!;
              widgets.add(pw.SizedBox(height: 16));
              widgets.add(
                pw.Text(
                  title,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              );
              widgets.add(pw.SizedBox(height: 6));
              widgets.add(_buildStatsSummary(results));
              widgets.add(pw.SizedBox(height: 10));
              widgets.add(
                _buildHistoricalPerformance('Historical Performance', results),
              );
              widgets.add(pw.Divider());
            }
            return widgets;
          },
        ),
      );
      return pdf.save();
    } catch (e) {
      final pdf = pw.Document();
      pdf.addPage(
        pw.Page(
          build: (c) => pw.Center(
            child: pw.Text(
              'Error generating report: $e',
              style: pw.TextStyle(color: PdfColors.red),
            ),
          ),
        ),
      );
      return pdf.save();
    }
  }

  // ---------- Styling and building blocks ----------
  static pw.Widget _buildHeader(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.blueGrey800,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              color: PdfColors.white,
              fontSize: 20,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
          pw.Text(
            _formatDate(DateTime.now()),
            style: pw.TextStyle(color: PdfColors.white, fontSize: 10),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildHeadline(String headline, String summary) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          headline,
          style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          summary,
          style: pw.TextStyle(fontSize: 14, color: PdfColors.grey600),
        ),
      ],
    );
  }

  static pw.Widget _buildSection(String title, List<ReportMetric> metrics) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Container(
          padding: const pw.EdgeInsets.all(8),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Column(
            children: metrics
                .map(
                  (m) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 2),
                    child: pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text(
                          m.label,
                          style: pw.TextStyle(color: PdfColors.grey700),
                        ),
                        pw.Text(
                          m.value,
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        ),
                      ],
                    ),
                  ),
                )
                .toList(),
          ),
        ),
      ],
    );
  }

  static pw.Widget _buildCoachTips(List<CoachTip> tips) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Coach\'s Tips',
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Container(
          padding: const pw.EdgeInsets.all(8),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(6),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: tips
                .map(
                  (t) => pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(vertical: 2),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          t.title,
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        ),
                        pw.Text(
                          t.description,
                          style: pw.TextStyle(color: PdfColors.grey700),
                        ),
                      ],
                    ),
                  ),
                )
                .toList(),
          ),
        ),
      ],
    );
  }

  // ---------- Historical Data (Stats + Chart + Table) ----------
  static (double? value, String unit) _parseResultValue(String input) {
    final trimmed = input.trim();
    if (trimmed.isEmpty) return (null, '');
    final parts = trimmed.split(RegExp(r'\s+'));
    final numPart = parts.isNotEmpty ? parts.first : '';
    final value = double.tryParse(numPart);
    final unit = parts.length > 1 ? parts.sublist(1).join(' ') : '';
    return (value, unit);
  }

  static bool _isHigherBetterForTest(String title, String unit) {
    final t = title.toLowerCase();
    const lowerBetterTitles = [
      '30mts standing start',
      '4*10mts shuttle run',
      '800mts run',
      '1.6km run',
    ];
    if (lowerBetterTitles.any((e) => t.contains(e.toLowerCase()))) return false;
    final u = unit.toLowerCase();
    const timeUnits = [
      'sec',
      'second',
      'seconds',
      's',
      'min',
      'minute',
      'minutes',
      'ms',
    ];
    if (timeUnits.any((kw) => u.contains(kw))) return false;
    return true; // default higher is better
  }

  static pw.Widget _metricRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(color: PdfColors.grey700)),
          pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  static pw.Widget _buildStatsSummary(List<TestResult> results) {
    final latest = results.last;
    final prev = results.length > 1 ? results[results.length - 2] : null;
    final (latestVal, latestUnit) = _parseResultValue(latest.resultValue);
    final (prevVal, _) = _parseResultValue(prev?.resultValue ?? '');

    final values = <double>[];
    for (final r in results) {
      final (v, _) = _parseResultValue(r.resultValue);
      if (v != null) values.add(v);
    }

    double? avg;
    double? best;
    DateTime? bestDate;
    if (values.isNotEmpty) {
      avg = values.reduce((a, b) => a + b) / values.length;
      final (_, unitProbe) = _parseResultValue(results.last.resultValue);
      final higherBetter = _isHigherBetterForTest(
        results.last.testTitle,
        unitProbe,
      );
      var bestIdx = 0;
      for (var i = 1; i < values.length; i++) {
        final better = higherBetter
            ? values[i] > values[bestIdx]
            : values[i] < values[bestIdx];
        if (better) bestIdx = i;
      }
      best = values[bestIdx];
      bestDate = results[bestIdx].date;
    }

    final change = (latestVal != null && prevVal != null)
        ? latestVal - prevVal
        : null;
    String fmt(double v) => v.toStringAsFixed(2);

    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Summary',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          _metricRow('Attempts', results.length.toString()),
          if (avg != null)
            _metricRow(
              'Average',
              '${fmt(avg)}${latestUnit.isNotEmpty ? ' ' + latestUnit : ''}',
            ),
          if (best != null && bestDate != null)
            _metricRow(
              'Best',
              '${fmt(best)}${latestUnit.isNotEmpty ? ' ' + latestUnit : ''} (${_formatDate(bestDate)})',
            ),
          if (latestVal != null)
            _metricRow(
              'Latest',
              '${fmt(latestVal)}${latestUnit.isNotEmpty ? ' ' + latestUnit : ''} (${_formatDate(results.last.date)})',
            ),
          _metricRow(
            'Change vs previous',
            change == null
                ? 'N/A'
                : '${change >= 0 ? '+' : ''}${fmt(change)}${latestUnit.isNotEmpty ? ' ' + latestUnit : ''}',
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildHistoricalPerformance(
    String title,
    List<TestResult> results,
  ) {
    final headers = ['Date', 'Result', 'Change'];
    final rows = <List<String>>[];
    for (var i = 0; i < results.length; i++) {
      final cur = results[i];
      final (curVal, unit) = _parseResultValue(cur.resultValue);
      String changeStr;
      if (i == 0) {
        changeStr = '—';
      } else {
        final (prevVal, _) = _parseResultValue(results[i - 1].resultValue);
        if (curVal != null && prevVal != null) {
          final d = curVal - prevVal;
          changeStr =
              '${d >= 0 ? '+' : ''}${d.toStringAsFixed(2)}${unit.isNotEmpty ? ' ' + unit : ''}';
        } else {
          changeStr = 'N/A';
        }
      }
      rows.add([_formatDate(cur.date), cur.resultValue, changeStr]);
    }

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 6),
        pw.Container(
          height: 160,
          child: () {
            final points = <pw.PointChartValue>[];
            for (var i = 0; i < results.length; i++) {
              final (v, _) = _parseResultValue(results[i].resultValue);
              final y = v ?? 0.0;
              points.add(pw.PointChartValue((i + 1).toDouble(), y));
            }
            if (points.isEmpty) return pw.SizedBox();
            double minY = points
                .map((p) => p.y)
                .reduce((a, b) => a < b ? a : b);
            double maxY = points
                .map((p) => p.y)
                .reduce((a, b) => a > b ? a : b);
            if (minY == maxY) {
              minY -= 1;
              maxY += 1;
            }
            if (minY > 0) minY = 0;
            final avgY =
                points.map((p) => p.y).fold<double>(0.0, (a, b) => a + b) /
                points.length;
            final tickCount = 6;
            final span = maxY - minY;
            final step = span / (tickCount - 1);
            final yTicks = List<double>.generate(
              tickCount,
              (i) => double.parse((minY + step * i).toStringAsFixed(2)),
            );
            final monthShort = const [
              'Jan',
              'Feb',
              'Mar',
              'Apr',
              'May',
              'Jun',
              'Jul',
              'Aug',
              'Sep',
              'Oct',
              'Nov',
              'Dec',
            ];
            final xLabels = List<String>.generate(points.length, (i) {
              final d = results[i].date;
              return '${d.day} ${monthShort[d.month - 1]}';
            });
            return pw.Chart(
              grid: pw.CartesianGrid(
                xAxis: pw.FixedAxis.fromStrings(
                  xLabels,
                  marginStart: 10,
                  marginEnd: 10,
                ),
                yAxis: pw.FixedAxis(
                  yTicks,
                  format: (v) => v.toStringAsFixed(2),
                ),
              ),
              datasets: [
                pw.LineDataSet(
                  data: points,
                  drawSurface: true,
                  legend: 'Result',
                  color: PdfColors.blue,
                  surfaceOpacity: 0.15,
                  lineWidth: 2,
                  pointSize: 3,
                ),
                pw.LineDataSet(
                  data: points
                      .map((p) => pw.PointChartValue(p.x, avgY))
                      .toList(),
                  legend: 'Average',
                  color: PdfColors.red,
                  drawSurface: false,
                  lineWidth: 1,
                  pointSize: 0,
                ),
              ],
            );
          }(),
        ),
        pw.SizedBox(height: 10),
        pw.Table.fromTextArray(
          headers: headers,
          data: rows,
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          headerDecoration: pw.BoxDecoration(color: PdfColors.grey300),
          cellAlignment: pw.Alignment.centerLeft,
        ),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by Sādhak • ${_formatDateTime(DateTime.now())}',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
          pw.Text(
            'Page ${context.pageNumber}/${context.pagesCount}',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
          ),
        ],
      ),
    );
  }

  static String _formatDate(DateTime d) => '${d.day}/${d.month}/${d.year}';
  static String _formatDateTime(DateTime d) =>
      '${_pad2(d.day)}/${_pad2(d.month)}/${d.year} ${_pad2(d.hour)}:${_pad2(d.minute)}';
  static String _pad2(int n) => n.toString().padLeft(2, '0');

  static Future<void> previewPdf(File file) async {
    await Printing.layoutPdf(onLayout: (_) => file.readAsBytes());
  }
}
